# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: infNaN
subtitle:
description: 多穿女装少踩坑
keywords:
author: infNaN
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://plusnan.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugin:
 - hexo-generator-category
 - hexo-generator-tag
 - hexo-generator-feed
 - hexo-generator-sitemap

feed:
  type: atom
  path: rss.xml
  limit: 20

sitemap:
  path: sitemap.xml

tag_generator:
  per_page: 0

category_generator:
  per_page: 0

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

html_minifier:
  enable: false
  collapseWhitespace: false
  removeEmptyAttributes: false
js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'
css_minifier:
  enable: false
  exclude: 
    - '*.min.css'
image_minifier: 
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

#disqus_proxy:
#  shortname: christ-wu-blog
#  username: proxy
#  host: disqus-proxy.plusnan.me
#  port: 443

## Themes: https://hexo.io/themes/
theme: hexo-theme-next
theme_config:
  author: infNaN
  description: 适量女装，有益身心
  language: zh-CN
  avatar:
    url: /img/myavatar.jpg
  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true

  scheme: Muse
  fancybox: false
  pangu: true

  disqus:
    enable: true
    shortname: plusnan
    count: true
  #disqusjs:
  #  enable: true
  #  # API Endpoint of Disqus API (https://disqus.com/api/)
  #  # leave api empty if you are able to connect to Disqus API
  #  # otherwise you need a reverse proxy for Disqus API
  #  # For example: 
  #  # api: https://disqus.skk.moe/disqus/
  #  api: https://disqus-proxy.plusnan.me/
  #  apikey: # register new application from https://disqus.com/api/applications/
  #  shortname: christ-wu-blog

  menu:
    home: / || home
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
  footer:
    since: 2018
    powered:
      enable: true
    theme:
      enable: true
  motion:
    enable: false
  #toc:
  #  wrap: true
  tabs:
    enable: true
    transition:
      tabs: false
      labels: false
    border_radius: 0
  site_state: true
  
  sidebar:
    position: right
    display: always

  social:
    GitHub: https://github.com/infnan || github
    E-Mail: mailto:me@plusnan.me || envelope
  social_icons:
    enable: true

  codeblock:
    highlight_theme: night
    copy_button:
      enable: true
      show_result: true

  exturl: true
  baidu_push: true
  font:
    enable: false
  note:
    style: simple
    icons: true
    border_radius: 3
    light_bg_offset: 0

  custom_file_path:
    variable: source/_data/variables.styl
    style: source/_data/styles.styl

  math:
    enable: true
    per_page: true
    engine: mathjax
    mathjax:
      cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  google_analytics: UA-134391990-1

#theme: hexo-theme-indigo
#theme_config:
#  # 添加新菜单项遵循以下规则
#  # menu:
#  #  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#  #    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#  #    url: /about       链接，绝对或相对路径，必须。
#  #    target: _blank    是否跳出，省略则在当前页面打开
#  menu:
#    home:
#      text: 主页
#      url: /
#    archives:
#      text: 存档
#      url: /archives
#    tags:
#      text: 标签
#      url: /tags
#    th-list:
#      text: 分类
#      url: /categories
#    github:
#      text: GitHub
#      url: https://github.com/infnan
#      target: _blank
#    rss:
#      text: RSS
#      url: /rss.xml
#      target: _blank
#
#  # 你的头像url
#  avatar: /img/myavatar.jpg
#  # avatar link
#  avatar_link: /
#
#  # email
#  email: 'me@plusnan.me'
#
#  # 设置 Android L Chrome 浏览器状态栏颜色
#  color: '#3F51B5'
#
#  # 页面标题
#  tags_title: 标签
#  archives_title: 存档
#  categories_title: 分类
#
#  # 文章截断
#  excerpt_render: true
#  #excerpt_length: 200
#  excerpt_link: 阅读全文...
#  mathjax: true
#  archive_yearly: true
#
#  # 是否显示文章最后更新时间
#  show_last_updated: true
#
#  # 是否开启分享
#  share: true
#
#  # 是否开启打赏，关闭 reward: false
#  reward: false
#
#  # 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
#  postMessage: ''
#
#  # 以下评论插件开启一个即可
#  # 是否开启 disqus
#  disqus_shortname: christ-wus-blog
#  # 版权起始年份
#  since_year: 2018
#
#  # 用户页面中作者相关的描述性文字，如不需要设为 false
#  about: false
#
#  # “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
#  visit_counter: false
#
#  # 动态定义title
#  title_change: false
#
#  # 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
#  # 如果想让你的自定义样式生效，把此项设为 false
#  cdn: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:infnan/infnan.github.io.git
  branch: master
